# Generated by Django 4.1.2 on 2022-10-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brandmodel_alter_productcolormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolormodel',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors '},
        ),
    ]
